sudo: false
language: ruby
cache: bundler
dist: xenial

services:
  - mysql
  - postgresql

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10-postgis-2.4

before_install:
  - gem install bundler

before_script:
  - mysql -e 'create database makara_test;'
  - psql -c 'create database makara_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres

rvm:
#  - 2.0
#  - 2.1
#  - 2.2
  - 2.3
  - 2.4
  - 2.5.0
  - ruby-head
  - jruby

gemfile:
#  - gemfiles/ar30.gemfile
#  - gemfiles/ar31.gemfile
#  - gemfiles/ar32.gemfile
#  - gemfiles/ar40.gemfile
#  - gemfiles/ar41.gemfile
#  - gemfiles/ar42.gemfile
  - gemfiles/ar50.gemfile
  - gemfiles/ar51.gemfile
  - gemfiles/ar60.gemfile
  - gemfiles/ar-head.gemfile

env:
  global:
    - "JRUBY_OPTS='--dev -J-Xmx1024M'"

matrix:
  exclude:
    - gemfile: gemfiles/ar30.gemfile
      rvm: 2.2
    - gemfile: gemfiles/ar30.gemfile
      rvm: 2.3
    - gemfile: gemfiles/ar30.gemfile
      rvm: 2.4
    - gemfile: gemfiles/ar31.gemfile
      rvm: 2.4
    - gemfile: gemfiles/ar32.gemfile
      rvm: 2.4
    - gemfile: gemfiles/ar40.gemfile
      rvm: 2.4
    - gemfile: gemfiles/ar41.gemfile
      rvm: 2.4
    - gemfile: gemfiles/ar30.gemfile
      rvm: 2.5.0
    - gemfile: gemfiles/ar31.gemfile
      rvm: 2.5.0
    - gemfile: gemfiles/ar32.gemfile
      rvm: 2.5.0
    - gemfile: gemfiles/ar40.gemfile
      rvm: 2.5.0
    - gemfile: gemfiles/ar41.gemfile
      rvm: 2.5.0
    - gemfile: gemfiles/ar30.gemfile
      rvm: ruby-head
    - gemfile: gemfiles/ar31.gemfile
      rvm: ruby-head
    - gemfile: gemfiles/ar32.gemfile
      rvm: ruby-head
    - gemfile: gemfiles/ar40.gemfile
      rvm: ruby-head
    - gemfile: gemfiles/ar41.gemfile
      rvm: ruby-head
    - gemfile: gemfiles/ar50.gemfile
      rvm: 2.0
    - gemfile: gemfiles/ar50.gemfile
      rvm: 2.1
    - gemfile: gemfiles/ar50.gemfile
      rvm: 2.2
    - gemfile: gemfiles/ar51.gemfile
      rvm: 2.0
    - gemfile: gemfiles/ar51.gemfile
      rvm: 2.1
    - gemfile: gemfiles/ar51.gemfile
      rvm: 2.2
    - gemfile: gemfiles/ar60.gemfile
      rvm: 2.0
    - gemfile: gemfiles/ar60.gemfile
      rvm: 2.1
    - gemfile: gemfiles/ar60.gemfile
      rvm: 2.2
    - gemfile: gemfiles/ar60.gemfile
      rvm: 2.3
    - gemfile: gemfiles/ar60.gemfile
      rvm: 2.4
    - gemfile: gemfiles/ar-head.gemfile
      rvm: 2.0
    - gemfile: gemfiles/ar-head.gemfile
      rvm: 2.1
    - gemfile: gemfiles/ar-head.gemfile
      rvm: 2.2
    - gemfile: gemfiles/ar-head.gemfile
      rvm: 2.3
    - gemfile: gemfiles/ar-head.gemfile
      rvm: 2.4
  allow_failures:
    - gemfile: gemfiles/ar-head.gemfile
    - rvm: ruby-head
    - rvm: jruby
  fast_finish: true
