language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

gemfile:
  - gemfiles/ar30.gemfile
  - gemfiles/ar31.gemfile
  - gemfiles/ar32.gemfile
  - gemfiles/ar40.gemfile

matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/ar40.gemfile